deck=Deck()
deck.shuffle()
dealer=Dealer()
player1=Player("player1", 100)
player2=Player("player2", 100)
PlayerList.append(player1)
PlayerList.append(player2)
dealer.dealCards(2, PlayerList, deck)
dealer.printPlayerCards(player1)
dealer.dealCards(1, [player1], deck)
dealer.printPlayerCards(player1)
